### ISSUE TITLE
handing of 64 bits integers missing

### ISSUE THREAD

**Issue by bstarynk** [hjson/hjson-cpp#12]
It seems that it is not possible to code reliably (on 64 bits systems like Linux/x86-64) something like:

    std::int64_t ii = 1000000*1000000; // don't fit in an int
    Hjson::Value hval(ii);

and of course get the same value later at parsing time.

[Basile Starynkevitch](http://starynkevitch.net/Basile/) working on [RefPerSys](http://refpersys.org/)

**Comment by trobro** [comment]
Thanks for pointing this out. In Javascript all numbers have traditionally been treated as doubles (64 bit floats), therefore I have done the same in the C++ implementation of Hjson, even though technically the original JSON specification says nothing about number precision.

I was not able to compile your example in Visual Studio 2017 because the compiler didn't know which overloaded constructor to use for `std::int64_t`. And also because the multiplication was treated as multiplication of two int32 values before implicit cast to int64 (so the variable `ii` contained a negative value due to overflow). But casting to `double` works for me:

```
  std::int64_t ii = 1000000;
  ii *= ii;
  Hjson::Value hval(static_cast<double>(ii));
  printf("%lld\n", static_cast<std::int64_t>(hval.to_double()));
```

Unfortunately `double` only gives 52 bit precision, not 64 bit.

I think I originally did try to add int64 constructor and operators, but ran into problems in some compilers that were complaining about ambiguous overloading. So I figured that needing int64 was less common than using that specific compiler (probably Visual Studio). Maybe I'll have a look at it again.

**Comment by bstarynk** [comment]
A possible way to overcome your compiler deficiency would be to define some empty `struct` as `public:` in your `HJson::Value`, for example:

    /// inside HJSon::Value, public:
    struct Int64_tag {};

then you could define a constructor:
    Value(std::int64_t i, Int64_tag);

and the user would call:

    HJson::Value hval(static_cast<std::int64_t>(x+3), Int64_tag{});

This is a bit noisy, but it enables you to have different constructor. Any decent optimizing C++ compiler (such as recent [GCC](http://gcc.gnu.org/) or [Clang](http://clang.llvm.org) on Linux) will not even generate any machine for the `Int64_tag{}` second argument.

**Comment by trobro** [comment]
Thanks for the suggestion!

I tested without tag now on Visual Studio 2015, VS 2017, gcc 5.4 and gcc 7.4, worked fine. Maybe it was instead problems with the return values from operators that originally made me choose to not support int64. I can't think of a convenient way to have arithmetic operators that can return either `double` or `int64`. And adding an operator `std::int64_t() const` causes errors like these for all compilers:

```
error: ambiguous overload for ‘operator==’ (operand types are ‘double’ and ‘const Hjson::Value’)
     assert(3.0 == val);
            ~~~~^~~~
note: candidate: operator==(double, int) <built-in>
note: candidate: operator==(double, double) <built-in>
note: candidate: operator==(double, int64_t {aka long int}) <built-in>
```

What I can do is add a function `to_int64()`. This works:

```
  std::int64_t ii = 1000000;
  ii *= ii;
  Hjson::Value hval(ii);
  printf("%lld\n", hval.to_int64());
  assert(hval.to_int64() == ii);
```

That would allow integers to be stored as `int64` internally, and extracted with full 64 bit precision using `to_int64()`. In any places where `to_int64()` is not used (for example `std::int64_t jj = hval + 1;`) the precision would only be 52 bit instead of 64, which isn't user friendly. But maybe it's the best compromise.

I would not add any public type `INT64`, since JSON and Javascript only have a `number` type, so it could be confusing to have two Hjson types both representing `number`.

**Comment by bstarynk** [comment]
On Friday, November 15, 2019 12:41 CET, trobro <notifications@github.com> wrote:
 
Thanks for the suggestion!
I tested without tag now on Visual Studio 2015, VS 2017, gcc 5.4 and gcc 7.4, worked fine.

You'll better use gcc 9.2. It is the current release of GCC.

You could compile GCC from its source code on your Linux distribution.

Cheers
--
Basile http://starynkevitch.net/Basile/

**Comment by bstarynk** [comment]
On Friday, November 15, 2019 12:41 CET, trobro <notifications@github.com> wrote:
 
What I can do is add a function to_int64(). This works:  std::int64_t ii = 1000000;
  ii *= ii;
  Hjson::Value hval(ii);
  printf("%lld\n", hval.to_int64());
  assert(hval.to_int64() == ii);

That would allow integers to be stored as int64 internally, and extracted with full 64 bit precision using to_int64().


 

For the RefPerSys project, that is enough.

Cheers
--
Basile Starynkevitch http://starynkevitch.net/Basile (near Paris, France)

**Comment by trobro** [comment]
I found the troublesome compiler: Clang on MacOS. But apparently C++11 does not allow integer promotion from `int` to `int64_t`, instead treats it as an conversion on equal level as e.g. conversion from `int` to `double`. So I chose to use your suggestion with the empty tag struct in the constructor.

Example:

```cpp
Hjson::Value myValue(9223372036854775807, Hjson::Int64_tag{});
assert(myValue.to_int64() == 9223372036854775807);
```

I've created a pull request and linked it to this issue, feel free to review it.
