### ISSUE TITLE
give written instructions to get a debug-friendly HjonCPP library on Linux

### ISSUE THREAD

**Issue by bstarynk** [hjson/hjson-cpp#19]
I am not familiar at all with [cmake](https://cmake.org/) on Linux (and honestly, I dislike it: it is hiding too much things). I much prefer [omake](http://projects.camlcity.org/projects/omake.html) or [ninja](http://ninja-build.org/) to `cmake`.

Could you please add a few lines in the [README.md](https://github.com/hjson/hjson-cpp/blob/master/README.md) about how to compile the HJson CPP library to get debug friendly information. On Linux with `g++` or `clang++` that would mean passing both `-g` and `-O1` to the C++  compiler (it is possible, and worthwhile, to have debugging symbols and a little optimization). Of course you won't `strip` the library.

BTW, I also miss a shared library on Linux, that is a `libhjsoncpp.so`. See Drepper's paper [*How to write shared libraries*](https://www.akkadia.org/drepper/dsohowto.pdf) for details, and the old [*Program Library HowTo*](http://tldp.org/HOWTO/Program-Library-HOWTO/)

Thanks a lot.

**Comment by bstarynk** [comment]
For what it worth, the following compilation command gives a shared library, with debug symbols, on Linux.
```
g++ -O -g -fPIC -Iinclude -Iinclude/hjson src/*.cpp \
      -Wl,-rpath -Wl,/usr/local/lib -shared -o /usr/local/lib/libhjson.so
```

then an `ldconfig` is needed, assuming `/etc/ld.so.conf` mentions `/usr/local/lib`

**Comment by trobro** [comment]
I recently added the section *Cmake options* in the *README.md*, it mentions both debug builds and shared libraries. I have chosen to concentrate only on Cmake in the documentation, since the important parts of the documentation will be harder to find the more things that are added to it.

This should be all you need to do in order to install a debug shared library, after that you won't need to use Cmake at all:

```
$ cd hjson-cpp
$ mkdir build
$ cd build
$ cmake .. -DHJSON_ENABLE_INSTALL=ON -DCMAKE_BUILD_TYPE=Debug -DBUILD_SHARED_LIBS=ON
$ sudo make install
```
